### ISSUE TITLE
Delete Comment button?

### ISSUE THREAD

**Issue by thujone** [maddiereddy/OpaGrappa#10]
https://github.com/maddiereddy/OpaGrappa/blob/c7f4aab5c5cc4c3601879b4199f7a3e9649b07de/public/edit-list.html#L57

Would be nice if there were a way to delete a comment, either with a button or even just a little X icon at the end of the comment. Something like that. I suppose the user could just empty the field if they want, but that doesn't seem like a common user interaction to make them do something like that.

I dunno, not 100% necessary, but I think it'd be nice.

**Comment by maddiereddy** [comment]
As removing a comment is the same as removing an item from the list in this version of the app, this issue is rather moot.
