### ISSUE TITLE
Tests look good!

### ISSUE THREAD

**Issue by thujone** [maddiereddy/OpaGrappa#12]
https://github.com/maddiereddy/OpaGrappa/blob/c7f4aab5c5cc4c3601879b4199f7a3e9649b07de/test/test-auth.js#L60

I'm not sure if usernames can be considered "incorrect" per se. They either exist or don't exist, but that's a very minor point. The tests themselves look just fine to me. Formatting-wise, it's better to add a blank line between each test, and some people add two blank lines between "describe" suites.

**Comment by maddiereddy** [comment]
done
