### ISSUE TITLE
New User creation confirmation

### ISSUE THREAD

**Issue by thujone** [maddiereddy/OpaGrappa#13]
https://github.com/maddiereddy/OpaGrappa/blob/c7f4aab5c5cc4c3601879b4199f7a3e9649b07de/test/test-users.js#L297

I guess I was a little confused by the registration flow, because when I finished registering, it just dumped me off at the login page. I guess there was a little message saying the user was created, but it wasn't clear that I had to log in again. And this was confusing to me, because I had already logged in as the demo user, and so the username and password fields were filled in with the demo username. Which seemed like a broken experience for me. I think you can at least say that I need to log in again after registering -- and prevent the fields from pre-populating with the old username/password.

**Comment by maddiereddy** [comment]
removed the re-login after creating an account. takes user directly into app after creating a login
