### ISSUE TITLE
Overall this file looks great

### ISSUE THREAD

**Issue by thujone** [maddiereddy/OpaGrappa#5]
https://github.com/maddiereddy/OpaGrappa/blob/c7f4aab5c5cc4c3601879b4199f7a3e9649b07de/server.js#L70

Minor formatting issue here. I'd sprinkle in a few comments, maybe just describing what each route is. It'd also be nice to put a jsdoc-style comment at the top of the js files.

**Comment by maddiereddy** [comment]
done
