### ISSUE TITLE
Different subdirectories for different asset types

### ISSUE THREAD

**Issue by thujone** [maddiereddy/OpaGrappa#6]
https://github.com/maddiereddy/OpaGrappa/blob/c7f4aab5c5cc4c3601879b4199f7a3e9649b07de/public/index.html#L1

Traditionally, .css files go in a subdirectory called 'stylesheets' or 'styles' or 'css'.

Javascript files typically go in a subdir called 'scripts' or 'js'.

HTML files typically stay in the top level of 'public'. Sometimes people create an 'html' subdir, which is totally fine, too. I would recommend creating new subdirs for stylesheets and scripts, especially considering you have an 'images' directory as well.

**Comment by maddiereddy** [comment]
done
