### ISSUE TITLE
Browser-specific prefixes for CSS transitions can be removed

### ISSUE THREAD

**Issue by thujone** [maddiereddy/OpaGrappa#7]
https://github.com/maddiereddy/OpaGrappa/blob/c7f4aab5c5cc4c3601879b4199f7a3e9649b07de/public/signup-login.css#L73

This is a handy site for CSS browser-specific prefixes:
http://shouldiprefix.com/

As you can see, the CSS3 transition rule does not require browser-specific prefixes any longer, so you can remove all these eye sores.

**Comment by maddiereddy** [comment]
done
