### ISSUE TITLE
Confusing button label

### ISSUE THREAD

**Issue by thujone** [maddiereddy/OpaGrappa#9]
https://github.com/maddiereddy/OpaGrappa/blob/c7f4aab5c5cc4c3601879b4199f7a3e9649b07de/public/edit-list.html#L56

I actually thought this was a bug when I first tried it out. I thought Edit Wine should save the wine, but it appeared that it was just going back to the list. As it turns out, it IS saving the wine, but there's no indication that that is what happened. I think a better label would be to "Save Comment," and it'd be super awesome if there were some indication that that the comment was saved. Maybe a notification on the list page?

**Comment by maddiereddy** [comment]
done
